version: 2

defaults: &defaults
    working_directory: ~/js-threads-client
    docker:
        - image: textile/builder:1.13.1
jobs:
    lint-test:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                name: install daemon
                background: true
                command: |
                    cd ~ && mkdir gosrc && cd gosrc
                    git clone https://github.com/textileio/go-textile-threads.git && cd go-textile-threads
                    go run daemon/main.go
            - run: npm install
            - run:
                name: Lint
                command: |
                    npm run lint
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - ./node_modules
            - run:
                name: Test
                command: |
                    mkdir -p allure-results
                    npm run test:node
            # - store_test_results:
            #     path: allure-results
            # - store_artifacts:
            #     path: allure-results
    deploy:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
            - restore_cache:
                key: node-v1-{{ checksum "package.json" }}-{{ arch }}
            - run: npm install
            - attach_workspace:
                at: ~/js-threads-client
            - run:
                name: Authenticate
                command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/js-threads-client/.npmrc
            - run:
                name: Publish Package
                command: npm publish --access=public --unsafe-perm

workflows:
    version: 2
    js-threads-client:
        jobs:
            - lint-test:
                filters:
                    tags:
                        only: /.*/
            - deploy:
                requires:
                    - lint-test
                filters:
                    tags:
                        only: /^v.*/
                    branches:
                        ignore: /.*/
